In [ ]:
import pandas as pd

In [ ]:
s = pd.Series(["banana", 42])
s

0    banana
1        42
dtype: object

In [ ]:
s = pd.Series(["banana", 42], index=['fruit', 'qty'])
s

fruit    banana
qty          42
dtype: object

In [ ]:
# 데이터 프레임 만들기
scientists = pd.DataFrame({
    "Name": ["홍길동", "김철수"],
    "Job": ["변호사", "회계사"],
    "Born": ["1987-04-09", "1978-05-05"],
    "Died": ["2005-04-05", "2025-04-09"],
    "age": ["37", "39"]
})
scientists

  Name  Job        Born        Died age
0  홍길동  변호사  1987-04-09  2005-04-05  37
1  김철수  회계사  1978-05-05  2025-04-09  39

In [ ]:
person = pd.DataFrame(
    data = {
    "Job": ["변호사", "회계사"],
    "Born": ["1987-04-09", "1978-05-05"],
    "Died": ["2005-04-05", "2025-04-09"],
    "Age": [37, 39]
    },
    index=["홍길동", "김철수"],
    columns=["Job", "Born", "Died", "Age"]
)
person

     Job        Born        Died  Age
홍길동  변호사  1987-04-09  2005-04-05   37
김철수  회계사  1978-05-05  2025-04-09   39

In [ ]:
# Series 다루기
first_row = person.loc["홍길동"]
first_row  # Series

Job            변호사
Born    1987-04-09
Died    2005-04-05
Age             37
Name: 홍길동, dtype: object

In [ ]:
first_row.index  # 속성

Index(['Job', 'Born', 'Died', 'Age'], dtype='str')

In [ ]:
first_row.values

array(['변호사', '1987-04-09', '2005-04-05', np.int64(37)], dtype=object)

In [ ]:
first_row.keys()

Index(['Job', 'Born', 'Died', 'Age'], dtype='str')

In [ ]:
first_row.index[0]

'Job'

In [ ]:
first_row.keys()[0]

'Job'

In [ ]:
ages = person["Age"]
ages

홍길동    37
김철수    39
Name: Age, dtype: int64

In [ ]:
print(ages.mean())
print(ages.min())
print(ages.std())

38.0
37
1.4142135623730951

In [ ]:
ages.max()

np.int64(39)

### Series와 boolean

In [ ]:
# 기술 통계량 계산하기
scientists = pd.read_csv('../data/scientists.csv')
scientists

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [ ]:
scientists.info

<bound method DataFrame.info of                    Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician>

In [ ]:
# 시리즈 추출
ages = scientists['Age']
ages

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
ages.describe()

count     8.000000
mean     59.125000
std      18.325918
min      37.000000
25%      44.000000
50%      58.500000
75%      68.750000
max      90.000000
Name: Age, dtype: float64

In [ ]:
ages[ages > ages.mean()]

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [ ]:
ages > ages.mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [ ]:
boolean_series = [
    True,
    False,
    True,
    False,
    True,
    False,
    True,
    False
]
boolean_series

[True, False, True, False, True, False, True, False]

In [ ]:
ages[boolean_series]

0    37
2    90
4    56
6    41
Name: Age, dtype: int64

In [ ]:
# 시리즈의 브로드케스팅 연산
# 1. 벡터와 벡터
ages + ages

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [ ]:
# 벡터와 스칼라
ages + 100

0    137
1    161
2    190
3    166
4    156
5    145
6    141
7    177
Name: Age, dtype: int64

In [ ]:
# 길이가 서로 다른 벡터 연산
print(pd.Series([1, 100]))
print(ages + pd.Series([1, 100]))

0      1
1    100
dtype: int64
0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [ ]:
ages

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
rev_ages = ages.sort_index(ascending=False)
rev_ages
ages의 인덱스를 뒤집기(False로 값주면)

SyntaxError: invalid syntax (3906400874.py, line 3)

In [ ]:
ages + rev_ages

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

### 03-3 데이터 프레임 다루기

# Markup은 옆공간 클릭후 + m

In [ ]:
scientists.index

RangeIndex(start=0, stop=8, step=1)

In [ ]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='str')

In [ ]:
scientists.values

array([['Rosaline Franklin', '1920-07-25', '1958-04-16', 37, 'Chemist'],
       ['William Gosset', '1876-06-13', '1937-10-16', 61, 'Statistician'],
       ['Florence Nightingale', '1820-05-12', '1910-08-13', 90, 'Nurse'],
       ['Marie Curie', '1867-11-07', '1934-07-04', 66, 'Chemist'],
       ['Rachel Carson', '1907-05-27', '1964-04-14', 56, 'Biologist'],
       ['John Snow', '1813-03-15', '1858-06-16', 45, 'Physician'],
       ['Alan Turing', '1912-06-23', '1954-06-07', 41,
        'Computer Scientist'],
       ['Johann Gauss', '1777-04-30', '1855-02-23', 77, 'Mathematician']],
      dtype=object)

In [ ]:
# 데이터 프레임을 불리언 추출
scientists.loc[scientists['Age'] > scientists['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [ ]:
scientists['Age'] > scientists['Age'].mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [ ]:
scientists[0:8:2]

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist

In [ ]:
df1 = df2 = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df1 + df2

    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

In [ ]:
df_added = df1.add(df2)
df_added

    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

In [ ]:
scientists + scientists

,Name,Born,Died,Age,Occupation
0,Rosaline FranklinRosaline Franklin,1920-07-251920-07-25,1958-04-161958-04-16,74,ChemistChemist
1,William GossetWilliam Gosset,1876-06-131876-06-13,1937-10-161937-10-16,122,StatisticianStatistician
2,Florence NightingaleFlorence Nightingale,1820-05-121820-05-12,1910-08-131910-08-13,180,NurseNurse
3,Marie CurieMarie Curie,1867-11-071867-11-07,1934-07-041934-07-04,132,ChemistChemist
4,Rachel CarsonRachel Carson,1907-05-271907-05-27,1964-04-141964-04-14,112,BiologistBiologist
5,John SnowJohn Snow,1813-03-151813-03-15,1858-06-161858-06-16,90,PhysicianPhysician
6,Alan TuringAlan Turing,1912-06-231912-06-23,1954-06-071954-06-07,82,Computer ScientistComputer Scientist
7,Johann GaussJohann Gauss,1777-04-301777-04-30,1855-02-231855-02-23,154,MathematicianMathematician

In [ ]:
scientists*2

,Name,Born,Died,Age,Occupation
0,Rosaline FranklinRosaline Franklin,1920-07-251920-07-25,1958-04-161958-04-16,74,ChemistChemist
1,William GossetWilliam Gosset,1876-06-131876-06-13,1937-10-161937-10-16,122,StatisticianStatistician
2,Florence NightingaleFlorence Nightingale,1820-05-121820-05-12,1910-08-131910-08-13,180,NurseNurse
3,Marie CurieMarie Curie,1867-11-071867-11-07,1934-07-041934-07-04,132,ChemistChemist
4,Rachel CarsonRachel Carson,1907-05-271907-05-27,1964-04-141964-04-14,112,BiologistBiologist
5,John SnowJohn Snow,1813-03-151813-03-15,1858-06-161858-06-16,90,PhysicianPhysician
6,Alan TuringAlan Turing,1912-06-231912-06-23,1954-06-071954-06-07,82,Computer ScientistComputer Scientist
7,Johann GaussJohann Gauss,1777-04-301777-04-30,1855-02-231855-02-23,154,MathematicianMathematician

In [ ]:
[scientists]*2

[                   Name        Born        Died  Age          Occupation
 0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
 1        William Gosset  1876-06-13  1937-10-16   61        Statistician
 2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
 3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
 4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
 5             John Snow  1813-03-15  1858-06-16   45           Physician
 6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
 7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician,
                    Name        Born        Died  Age          Occupation
 0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
 1        William Gosset  1876-06-13  1937-10-16   61        Statistician
 2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
 3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
 4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
 5             John Snow  1813-03-15  1858-06-16   45           Physician
 6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
 7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician]

In [ ]:
scientists.dtypes

Name            str
Born            str
Died            str
Age           int64
Occupation      str
dtype: object

In [ ]:
born_datetime = pd.to_datetime(scientists['Born'], format='%Y-%m-%d') # 파이썬 날짜 포맷 참조
born_datetime

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[us]

In [ ]:
scientists['Born']

0    1920-07-25
1    1876-06-13
2    1820-05-12
3    1867-11-07
4    1907-05-27
5    1813-03-15
6    1912-06-23
7    1777-04-30
Name: Born, dtype: str

In [ ]:
died_datetime = pd.to_datetime(scientists['Died'], format='%Y-%m-%d')
died_datetime

0   1958-04-16
1   1937-10-16
2   1910-08-13
3   1934-07-04
4   1964-04-14
5   1858-06-16
6   1954-06-07
7   1855-02-23
Name: Died, dtype: datetime64[us]

In [ ]:
scientists['born-dt'], scientists['died-dt'] = (born_datetime, died_datetime)

In [ ]:
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23

In [ ]:
scientists.dtypes

Name                     str
Born                     str
Died                     str
Age                    int64
Occupation               str
born-dt       datetime64[us]
died-dt       datetime64[us]
dtype: object

In [ ]:
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23

In [ ]:
import numpy as np

scientists = scientists.assign(
    age_days_assign = scientists['died-dt'] - scientists['born-dt'],
    age_year_assign = lambda df_:
     (df_["age_days_assign"].dt.days/365).apply(np.floor),
    )

scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt,age_days_assign,age_year_assign
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16,13779 days,37.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16,22404 days,61.0
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13,32964 days,90.0
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04,24345 days,66.0
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14,20777 days,56.0
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16,16529 days,45.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07,15324 days,41.0
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23,28422 days,77.0

In [ ]:
scientists.dtypes

Name                           str
Born                           str
Died                           str
Age                          int64
Occupation                     str
born-dt             datetime64[us]
died-dt             datetime64[us]
age_days_assign    timedelta64[us]
age_year_assign            float64
dtype: object

In [ ]:
# 무작위 섞기(sample), 값을 섞기
scientists['Age'] = scientists['Age'].sample(frac=1, random_state=42).values
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt,age_days_assign,age_year_assign
0,Rosaline Franklin,1920-07-25,1958-04-16,90,Chemist,1920-07-25,1958-04-16,13779 days,37.0
1,William Gosset,1876-06-13,1937-10-16,37,Statistician,1876-06-13,1937-10-16,22404 days,61.0
2,Florence Nightingale,1820-05-12,1910-08-13,56,Nurse,1820-05-12,1910-08-13,32964 days,90.0
3,Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days,66.0
4,Rachel Carson,1907-05-27,1964-04-14,45,Biologist,1907-05-27,1964-04-14,20777 days,56.0
5,John Snow,1813-03-15,1858-06-16,61,Physician,1813-03-15,1858-06-16,16529 days,45.0
6,Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days,41.0
7,Johann Gauss,1777-04-30,1855-02-23,41,Mathematician,1777-04-30,1855-02-23,28422 days,77.0

In [ ]:
# index 섞기

scientists['Age'] = scientists['Age'].sample(frac=1, random_state=42)
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt,age_days_assign,age_year_assign
0,Rosaline Franklin,1920-07-25,1958-04-16,90,Chemist,1920-07-25,1958-04-16,13779 days,37.0
1,William Gosset,1876-06-13,1937-10-16,37,Statistician,1876-06-13,1937-10-16,22404 days,61.0
2,Florence Nightingale,1820-05-12,1910-08-13,56,Nurse,1820-05-12,1910-08-13,32964 days,90.0
3,Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days,66.0
4,Rachel Carson,1907-05-27,1964-04-14,45,Biologist,1907-05-27,1964-04-14,20777 days,56.0
5,John Snow,1813-03-15,1858-06-16,61,Physician,1813-03-15,1858-06-16,16529 days,45.0
6,Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days,41.0
7,Johann Gauss,1777-04-30,1855-02-23,41,Mathematician,1777-04-30,1855-02-23,28422 days,77.0

In [ ]:
scientists_dropped = scientists.drop(['Age'], axis="columns")
scientists_dropped

,Name,Born,Died,Occupation,born-dt,died-dt,age_days_assign,age_year_assign
0,Rosaline Franklin,1920-07-25,1958-04-16,Chemist,1920-07-25,1958-04-16,13779 days,37.0
1,William Gosset,1876-06-13,1937-10-16,Statistician,1876-06-13,1937-10-16,22404 days,61.0
2,Florence Nightingale,1820-05-12,1910-08-13,Nurse,1820-05-12,1910-08-13,32964 days,90.0
3,Marie Curie,1867-11-07,1934-07-04,Chemist,1867-11-07,1934-07-04,24345 days,66.0
4,Rachel Carson,1907-05-27,1964-04-14,Biologist,1907-05-27,1964-04-14,20777 days,56.0
5,John Snow,1813-03-15,1858-06-16,Physician,1813-03-15,1858-06-16,16529 days,45.0
6,Alan Turing,1912-06-23,1954-06-07,Computer Scientist,1912-06-23,1954-06-07,15324 days,41.0
7,Johann Gauss,1777-04-30,1855-02-23,Mathematician,1777-04-30,1855-02-23,28422 days,77.0

In [ ]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

WARNING: Cache entry deserialization failed, entry ignored

In [ ]:
scientists.to_csv('../output/scientsts_df.csv', index=False)

In [ ]:
scientists.to_excel("../output/scientists_df.xlsx", sheet_name="scientists", index=False)

PermissionError: [Errno 13] Permission denied: '../output/scientists_df.xlsx'