In [164]:
import pandas as pd

df1 = pd.read_csv('../data/concat_1.csv')
df2 = pd.read_csv('../data/concat_2.csv')
df3 = pd.read_csv('../data/concat_3.csv')
print(df1)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [165]:
print(df2)

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [166]:
print(df3)

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [167]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [168]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [169]:
df1.values

array([['a0', 'b0', 'c0', 'd0'],
       ['a1', 'b1', 'c1', 'd1'],
       ['a2', 'b2', 'c2', 'd2'],
       ['a3', 'b3', 'c3', 'd3']], dtype=object)

In [170]:
row_concat = pd.concat([df1, df2, df3])
print(row_concat)

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [171]:
print(row_concat.iloc[3, :])

A    a3
B    b3
C    c3
D    d3
Name: 3, dtype: str

In [172]:
new_row_series = pd.Series(['n1', 'n2', 'n3', 'n4'])
print(new_row_series)

0    n1
1    n2
2    n3
3    n4
dtype: str

In [173]:
print(pd.concat([df1, new_row_series], axis='columns'))

    A   B   C   D   0
0  a0  b0  c0  d0  n1
1  a1  b1  c1  d1  n2
2  a2  b2  c2  d2  n3
3  a3  b3  c3  d3  n4

In [174]:
col_concat_column = pd.concat([df1, new_row_series.rename('E')], axis='columns', )
col_concat_column

    A   B   C   D   E
0  a0  b0  c0  d0  n1
1  a1  b1  c1  d1  n2
2  a2  b2  c2  d2  n3
3  a3  b3  c3  d3  n4

In [175]:
new_row_df = pd.DataFrame(
    data = [['n1', 'n2', 'n3', 'n4']],
    columns = ['A', 'B', 'C', 'D']
)

print(new_row_df)

    A   B   C   D
0  n1  n2  n3  n4

In [176]:
print(pd.concat([df1, new_row_df]))

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  n1  n2  n3  n4

In [177]:
row_concat_i = pd.concat([df1, df2, df3], ignore_index=True)
print(row_concat_i)

      A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [178]:
col_concat = pd.concat([df1, df2, df3], axis = 'columns')
print(col_concat)

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [179]:
print(col_concat['A'])

    A   A    A
0  a0  a4   a8
1  a1  a5   a9
2  a2  a6  a10
3  a3  a7  a11

In [180]:
col_concat['new_col_list'] = ['n1', 'n2', 'n3', 'n4']
print(col_concat)

    A   B   C   D   A   B   C   D    A    B    C    D new_col_list
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8           n1
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9           n2
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10           n3
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11           n4

In [181]:
col_concat['new_col_series'] = pd.Series(['n1', 'n2', 'n3', 'n4'])
print(col_concat)

    A   B   C   D   A   B   C   D    A    B    C    D new_col_list  \
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8           n1
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9           n2
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10           n3
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11           n4

  new_col_series
0             n1
1             n2
2             n3
3             n4

In [182]:
print(pd.concat([df1, df2, df3], axis='columns', ignore_index=True))

   0   1   2   3   4   5   6   7    8    9    10   11
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [183]:
# 인덱스도 다르고 열이름도 다른 데이터 연결하기

In [184]:
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['E', 'F', 'G', 'H']
df3.columns = ['A', 'C', 'F', 'H']

print(df1)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [185]:
print(df2)

    E   F   G   H
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [186]:
print(df3)

     A    C    F    H
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [187]:
row_concat = pd.concat([df1, df2, df3])
row_concat

     A    B    C    D    E    F    G    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   a4   b4   c4   d4
1  NaN  NaN  NaN  NaN   a5   b5   c5   d5
2  NaN  NaN  NaN  NaN   a6   b6   c6   d6
3  NaN  NaN  NaN  NaN   a7   b7   c7   d7
0   a8  NaN   b8  NaN  NaN   c8  NaN   d8
1   a9  NaN   b9  NaN  NaN   c9  NaN   d9
2  a10  NaN  b10  NaN  NaN  c10  NaN  d10
3  a11  NaN  b11  NaN  NaN  c11  NaN  d11

In [188]:
print(pd.concat([df1, df2, df3], join='inner')) # join='inner'는 교집합을 의미

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

In [189]:
print(pd.concat([df1, df3], ignore_index=False, join='inner'))

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
0   a8   b8
1   a9   b9
2  a10  b10
3  a11  b11

In [190]:
print(pd.concat([df1, df3], ignore_index=True, join='inner'))

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
4   a8   b8
5   a9   b9
6  a10  b10
7  a11  b11

In [191]:
# 인덱스가 다른 데이터 열 발향 연결하기

In [192]:
df1.index = [0, 1, 2, 3]
df2.index = [4, 5, 6, 7]
df3.index = [0, 2, 5, 7]

print(df1)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [193]:
print(df2)

    E   F   G   H
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7

In [194]:
print(df3)

     A    C    F    H
0   a8   b8   c8   d8
2   a9   b9   c9   d9
5  a10  b10  c10  d10
7  a11  b11  c11  d11

In [195]:
col_concat = pd.concat([df1, df2, df3], axis='columns')
print(col_concat)

     A    B    C    D    E    F    G    H    A    C    F    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5  a10  b10  c10  d10
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7  a11  b11  c11  d11

In [196]:
print(pd.concat([df1, df3], axis='columns', join='inner'))

    A   B   C   D   A   C   F   H
0  a0  b0  c0  d0  a8  b8  c8  d8
2  a2  b2  c2  d2  a9  b9  c9  d9

In [197]:
# 분할된 데이터 연결하기

In [198]:
from pathlib import Path

billboard_data_files = (
    Path(".")
    .glob('../data/billboard_by_week/billboard-*.csv')
)

billboard_data_files = sorted(list(billboard_data_files))
print(billboard_data_files)
print(type(billboard_data_files))

[WindowsPath('../data/billboard_by_week/billboard-01.csv'), WindowsPath('../data/billboard_by_week/billboard-02.csv'), WindowsPath('../data/billboard_by_week/billboard-03.csv'), WindowsPath('../data/billboard_by_week/billboard-04.csv'), WindowsPath('../data/billboard_by_week/billboard-05.csv'), WindowsPath('../data/billboard_by_week/billboard-06.csv'), WindowsPath('../data/billboard_by_week/billboard-07.csv'), WindowsPath('../data/billboard_by_week/billboard-08.csv'), WindowsPath('../data/billboard_by_week/billboard-09.csv'), WindowsPath('../data/billboard_by_week/billboard-10.csv'), WindowsPath('../data/billboard_by_week/billboard-11.csv'), WindowsPath('../data/billboard_by_week/billboard-12.csv'), WindowsPath('../data/billboard_by_week/billboard-13.csv'), WindowsPath('../data/billboard_by_week/billboard-14.csv'), WindowsPath('../data/billboard_by_week/billboard-15.csv'), WindowsPath('../data/billboard_by_week/billboard-16.csv'), WindowsPath('../data/billboard_by_week/billboard-17.csv'), WindowsPath('../data/billboard_by_week/billboard-18.csv'), WindowsPath('../data/billboard_by_week/billboard-19.csv'), WindowsPath('../data/billboard_by_week/billboard-20.csv'), WindowsPath('../data/billboard_by_week/billboard-21.csv'), WindowsPath('../data/billboard_by_week/billboard-22.csv'), WindowsPath('../data/billboard_by_week/billboard-23.csv'), WindowsPath('../data/billboard_by_week/billboard-24.csv'), WindowsPath('../data/billboard_by_week/billboard-25.csv'), WindowsPath('../data/billboard_by_week/billboard-26.csv'), WindowsPath('../data/billboard_by_week/billboard-27.csv'), WindowsPath('../data/billboard_by_week/billboard-28.csv'), WindowsPath('../data/billboard_by_week/billboard-29.csv'), WindowsPath('../data/billboard_by_week/billboard-30.csv'), WindowsPath('../data/billboard_by_week/billboard-31.csv'), WindowsPath('../data/billboard_by_week/billboard-32.csv'), WindowsPath('../data/billboard_by_week/billboard-33.csv'), WindowsPath('../data/billboard_by_week/billboard-34.csv'), WindowsPath('../data/billboard_by_week/billboard-35.csv'), WindowsPath('../data/billboard_by_week/billboard-36.csv'), WindowsPath('../data/billboard_by_week/billboard-37.csv'), WindowsPath('../data/billboard_by_week/billboard-38.csv'), WindowsPath('../data/billboard_by_week/billboard-39.csv'), WindowsPath('../data/billboard_by_week/billboard-40.csv'), WindowsPath('../data/billboard_by_week/billboard-41.csv'), WindowsPath('../data/billboard_by_week/billboard-42.csv'), WindowsPath('../data/billboard_by_week/billboard-43.csv'), WindowsPath('../data/billboard_by_week/billboard-44.csv'), WindowsPath('../data/billboard_by_week/billboard-45.csv'), WindowsPath('../data/billboard_by_week/billboard-46.csv'), WindowsPath('../data/billboard_by_week/billboard-47.csv'), WindowsPath('../data/billboard_by_week/billboard-48.csv'), WindowsPath('../data/billboard_by_week/billboard-49.csv'), WindowsPath('../data/billboard_by_week/billboard-50.csv'), WindowsPath('../data/billboard_by_week/billboard-51.csv'), WindowsPath('../data/billboard_by_week/billboard-52.csv'), WindowsPath('../data/billboard_by_week/billboard-53.csv'), WindowsPath('../data/billboard_by_week/billboard-54.csv'), WindowsPath('../data/billboard_by_week/billboard-55.csv'), WindowsPath('../data/billboard_by_week/billboard-56.csv'), WindowsPath('../data/billboard_by_week/billboard-57.csv'), WindowsPath('../data/billboard_by_week/billboard-58.csv'), WindowsPath('../data/billboard_by_week/billboard-59.csv'), WindowsPath('../data/billboard_by_week/billboard-60.csv'), WindowsPath('../data/billboard_by_week/billboard-61.csv'), WindowsPath('../data/billboard_by_week/billboard-62.csv'), WindowsPath('../data/billboard_by_week/billboard-63.csv'), WindowsPath('../data/billboard_by_week/billboard-64.csv'), WindowsPath('../data/billboard_by_week/billboard-65.csv'), WindowsPath('../data/billboard_by_week/billboard-66.csv'), WindowsPath('../data/billboard_by_week/billboard-67.csv'), WindowsPath('../data/billboard_by_week/billboard-68.csv'), WindowsPath('../data/billboard_by_week/billboard-69.csv'), WindowsPath('../data/billboard_by_week/billboard-70.csv'), WindowsPath('../data/billboard_by_week/billboard-71.csv'), WindowsPath('../data/billboard_by_week/billboard-72.csv'), WindowsPath('../data/billboard_by_week/billboard-73.csv'), WindowsPath('../data/billboard_by_week/billboard-74.csv'), WindowsPath('../data/billboard_by_week/billboard-75.csv'), WindowsPath('../data/billboard_by_week/billboard-76.csv')]
<class 'list'>

In [199]:
billboard_data_files = list(billboard_data_files)
billboard_data_files

[WindowsPath('../data/billboard_by_week/billboard-01.csv'),
 WindowsPath('../data/billboard_by_week/billboard-02.csv'),
 WindowsPath('../data/billboard_by_week/billboard-03.csv'),
 WindowsPath('../data/billboard_by_week/billboard-04.csv'),
 WindowsPath('../data/billboard_by_week/billboard-05.csv'),
 WindowsPath('../data/billboard_by_week/billboard-06.csv'),
 WindowsPath('../data/billboard_by_week/billboard-07.csv'),
 WindowsPath('../data/billboard_by_week/billboard-08.csv'),
 WindowsPath('../data/billboard_by_week/billboard-09.csv'),
 WindowsPath('../data/billboard_by_week/billboard-10.csv'),
 WindowsPath('../data/billboard_by_week/billboard-11.csv'),
 WindowsPath('../data/billboard_by_week/billboard-12.csv'),
 WindowsPath('../data/billboard_by_week/billboard-13.csv'),
 WindowsPath('../data/billboard_by_week/billboard-14.csv'),
 WindowsPath('../data/billboard_by_week/billboard-15.csv'),
 WindowsPath('../data/billboard_by_week/billboard-16.csv'),
 WindowsPath('../data/billboard_by_week/billboard-17.csv'),
 WindowsPath('../data/billboard_by_week/billboard-18.csv'),
 WindowsPath('../data/billboard_by_week/billboard-19.csv'),
 WindowsPath('../data/billboard_by_week/billboard-20.csv'),
 WindowsPath('../data/billboard_by_week/billboard-21.csv'),
 WindowsPath('../data/billboard_by_week/billboard-22.csv'),
 WindowsPath('../data/billboard_by_week/billboard-23.csv'),
 WindowsPath('../data/billboard_by_week/billboard-24.csv'),
 WindowsPath('../data/billboard_by_week/billboard-25.csv'),
 WindowsPath('../data/billboard_by_week/billboard-26.csv'),
 WindowsPath('../data/billboard_by_week/billboard-27.csv'),
 WindowsPath('../data/billboard_by_week/billboard-28.csv'),
 WindowsPath('../data/billboard_by_week/billboard-29.csv'),
 WindowsPath('../data/billboard_by_week/billboard-30.csv'),
 WindowsPath('../data/billboard_by_week/billboard-31.csv'),
 WindowsPath('../data/billboard_by_week/billboard-32.csv'),
 WindowsPath('../data/billboard_by_week/billboard-33.csv'),
 WindowsPath('../data/billboard_by_week/billboard-34.csv'),
 WindowsPath('../data/billboard_by_week/billboard-35.csv'),
 WindowsPath('../data/billboard_by_week/billboard-36.csv'),
 WindowsPath('../data/billboard_by_week/billboard-37.csv'),
 WindowsPath('../data/billboard_by_week/billboard-38.csv'),
 WindowsPath('../data/billboard_by_week/billboard-39.csv'),
 WindowsPath('../data/billboard_by_week/billboard-40.csv'),
 WindowsPath('../data/billboard_by_week/billboard-41.csv'),
 WindowsPath('../data/billboard_by_week/billboard-42.csv'),
 WindowsPath('../data/billboard_by_week/billboard-43.csv'),
 WindowsPath('../data/billboard_by_week/billboard-44.csv'),
 WindowsPath('../data/billboard_by_week/billboard-45.csv'),
 WindowsPath('../data/billboard_by_week/billboard-46.csv'),
 WindowsPath('../data/billboard_by_week/billboard-47.csv'),
 WindowsPath('../data/billboard_by_week/billboard-48.csv'),
 WindowsPath('../data/billboard_by_week/billboard-49.csv'),
 WindowsPath('../data/billboard_by_week/billboard-50.csv'),
 WindowsPath('../data/billboard_by_week/billboard-51.csv'),
 WindowsPath('../data/billboard_by_week/billboard-52.csv'),
 WindowsPath('../data/billboard_by_week/billboard-53.csv'),
 WindowsPath('../data/billboard_by_week/billboard-54.csv'),
 WindowsPath('../data/billboard_by_week/billboard-55.csv'),
 WindowsPath('../data/billboard_by_week/billboard-56.csv'),
 WindowsPath('../data/billboard_by_week/billboard-57.csv'),
 WindowsPath('../data/billboard_by_week/billboard-58.csv'),
 WindowsPath('../data/billboard_by_week/billboard-59.csv'),
 WindowsPath('../data/billboard_by_week/billboard-60.csv'),
 WindowsPath('../data/billboard_by_week/billboard-61.csv'),
 WindowsPath('../data/billboard_by_week/billboard-62.csv'),
 WindowsPath('../data/billboard_by_week/billboard-63.csv'),
 WindowsPath('../data/billboard_by_week/billboard-64.csv'),
 WindowsPath('../data/billboard_by_week/billboard-65.csv'),
 WindowsPath('../data/billboard_by_week/billboard-66.csv'),
 WindowsPath('../data/billboard_by_week/billboard-67.csv'),
 WindowsPath('../data/billboard_by_week/billboard-68.csv'),
 WindowsPath('../data/billboard_by_week/billboard-69.csv'),
 WindowsPath('../data/billboard_by_week/billboard-70.csv'),
 WindowsPath('../data/billboard_by_week/billboard-71.csv'),
 WindowsPath('../data/billboard_by_week/billboard-72.csv'),
 WindowsPath('../data/billboard_by_week/billboard-73.csv'),
 WindowsPath('../data/billboard_by_week/billboard-74.csv'),
 WindowsPath('../data/billboard_by_week/billboard-75.csv'),
 WindowsPath('../data/billboard_by_week/billboard-76.csv')]

In [200]:
billboard01 = pd.read_csv(billboard_data_files[0])
billboard02 = pd.read_csv(billboard_data_files[1])
billboard03 = pd.read_csv(billboard_data_files[2])

print(billboard03)

     year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk3
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk3
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk3
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk3
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk3
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk3
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk3
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk3
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk3
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk3

     rating
0      72.0
1      92.0
2      68.0
3      72.0
4      25.0
..      ...
312    77.0
313    83.0
314    91.0
315     NaN
316    29.0

[317 rows x 7 columns]

In [201]:
print(billboard01.shape)
print(billboard02.shape)
print(billboard03.shape)

(317, 7)
(317, 7)
(317, 7)

In [202]:
billboard = pd.concat([billboard01, billboard02, billboard03])
# 연결한 데이터프레임의 shape확인
print(billboard.shape)

(951, 7)

In [203]:
billboard.head()

   year        artist                    track  time date.entered week  rating
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1    91.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08  wk1    81.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21  wk1    76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1    57.0

In [204]:
billboard.tail()

,year,artist,track,time,date.entered,week,rating
312,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,wk3,77.0
313,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,wk3,83.0
314,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,wk3,91.0
315,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk3,NaN
316,2000,matchbox twenty,Bent,4:12,2000-04-29,wk3,29.0

In [205]:
assert(
    billboard01.shape[0]
    + billboard02.shape[0]
    + billboard03.shape[0]
    == billboard.shape[0]
)

# assert의 의미는 01, 02, 03의 합이 billboard.shape과 같아야 한다는 것을 확인하는 작업
# 실행했을때 아무것도 나오지 않아야 문제가 없다는 의미

In [206]:
from pathlib import Path

billboard_data_files = (
    Path('.')
    .glob('../data/billboard_by_week/billboard-*.csv')
)

# 빈 리스트를 생성한다
list_billboard_df = []

# CSV 파일명 리스트를 순회합니다.
for csv_filename in billboard_data_files:
    
    # 필요하다면 아래 코드를 주석 해제하여 각 csv 파일명을 출력하세요
    # print(csv_filename)

    # CSV 파일을 DataFrame으로 불러온다
    df = pd.read_csv(csv_filename)

    # DataFrame을 리스트에 저장한다.
    list_billboard_df.append(df)

# DataFrame의 개수를 출력한다
print(len(list_billboard_df))

76

In [207]:
print(type(list_billboard_df[0]))

<class 'pandas.DataFrame'>

In [208]:
print(list_billboard_df[0])

     year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk1
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk1
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk1
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk1
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk1
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk1
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk1

     rating
0      87.0
1      91.0
2      81.0
3      76.0
4      57.0
..      ...
312    86.0
313    85.0
314    95.0
315    99.0
316    60.0

[317 rows x 7 columns]

In [209]:
billboard_loop_concat = pd.concat(list_billboard_df)
print(billboard_loop_concat.shape)

(24092, 7)

In [210]:
# list comprehension으로 여러 개 파일 불러오기
# for문을 리스트안에 넣기

In [211]:
from pathlib import Path

billboard_data_files = (
    Path(".")
    .glob('../data/billboard_by_week/billboard-*.csv')
)

list_billboard_df = []
for csv_filename in billboard_data_files:
    df = pd.read_csv(csv_filename)
    list_billboard_df.append(df)

billboard_data_files = (
    Path('.')
    .glob('../data/billboard_by_week/billboard-*.csv')
)

billboard_dfs = [pd.read_csv(data) for data in billboard_data_files] # 본 list comprehension이 아래 4줄을 대체한다
# list_billboard_df = []
# for csv_filename in billboard_data_files:
#     df = pd.read_csv(csv_filename)
#     list_billboard_df.append(df)

In [212]:
print(type(billboard_dfs))

<class 'list'>

In [213]:
print(len(billboard_dfs))

76

In [214]:
billboard_concat_comp = pd.concat(billboard_dfs)
print(billboard_dfs)

[     year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk1
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk1
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk1
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk1
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk1
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk1
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk1

     rating
0      87.0
1      91.0
2      81.0
3      76.0
4      57.0
..      ...
312    86.0
313    85.0
314    95.0
315    99.0
316    60.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk2
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk2
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk2
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk2
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk2
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk2
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk2
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk2
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk2
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk2

     rating
0      82.0
1      87.0
2      70.0
3      76.0
4      34.0
..      ...
312    83.0
313    83.0
314    94.0
315    99.0
316    37.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk3
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk3
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk3
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk3
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk3
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk3
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk3
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk3
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk3
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk3

     rating
0      72.0
1      92.0
2      68.0
3      72.0
4      25.0
..      ...
312    77.0
313    83.0
314    91.0
315     NaN
316    29.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk4
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk4
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk4
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk4
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk4
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk4
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk4
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk4
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk4
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk4

     rating
0      77.0
1       NaN
2      67.0
3      69.0
4      17.0
..      ...
312    74.0
313    82.0
314    85.0
315     NaN
316    24.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk5
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk5
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk5
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk5
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk5
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk5
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk5
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk5
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk5
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk5

     rating
0      87.0
1       NaN
2      66.0
3      67.0
4      17.0
..      ...
312    83.0
313    81.0
314    84.0
315     NaN
316    22.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk6
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk6
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk6
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk6
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk6
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk6
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk6
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk6
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk6
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk6

     rating
0      94.0
1       NaN
2      57.0
3      65.0
4      31.0
..      ...
312    79.0
313    91.0
314    78.0
315     NaN
316    21.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk7
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk7
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk7
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk7
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk7
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk7
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk7
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk7
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk7
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk7

     rating
0      99.0
1       NaN
2      54.0
3      55.0
4      36.0
..      ...
312    88.0
313     NaN
314    74.0
315     NaN
316    18.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk8
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk8
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk8
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk8
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk8
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk8
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk8
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk8
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk8
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk8

     rating
0       NaN
1       NaN
2      53.0
3      59.0
4      49.0
..      ...
312    95.0
313     NaN
314    78.0
315     NaN
316    16.0

[317 rows x 7 columns],      year            artist                    track  time date.entered week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk9
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk9
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk9
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk9
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk9
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk9
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk9
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk9
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk9
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk9

     rating
0       NaN
1       NaN
2      51.0
3      62.0
4      53.0
..      ...
312     NaN
313     NaN
314    85.0
315     NaN
316    13.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk10
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk10
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk10
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk10
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk10
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk10
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk10
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk10
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk10
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk10

     rating
0       NaN
1       NaN
2      51.0
3      61.0
4      57.0
..      ...
312     NaN
313     NaN
314    89.0
315     NaN
316    12.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk11
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk11
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk11
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk11
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk11
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk11
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk11
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk11
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk11
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk11

     rating
0       NaN
1       NaN
2      51.0
3      61.0
4      64.0
..      ...
312     NaN
313     NaN
314    97.0
315     NaN
316     8.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk12
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk12
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk12
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk12
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk12
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk12
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk12
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk12
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk12
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk12

     rating
0       NaN
1       NaN
2      51.0
3      59.0
4      70.0
..      ...
312     NaN
313     NaN
314    96.0
315     NaN
316     6.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk13
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk13
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk13
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk13
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk13
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk13
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk13
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk13
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk13
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk13

     rating
0       NaN
1       NaN
2      47.0
3      61.0
4      75.0
..      ...
312     NaN
313     NaN
314    99.0
315     NaN
316     1.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk14
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk14
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk14
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk14
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk14
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk14
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk14
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk14
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk14
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk14

     rating
0       NaN
1       NaN
2      44.0
3      66.0
4      76.0
..      ...
312     NaN
313     NaN
314    99.0
315     NaN
316     2.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk15
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk15
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk15
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk15
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk15
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk15
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk15
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk15
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk15
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk15

     rating
0       NaN
1       NaN
2      38.0
3      72.0
4      78.0
..      ...
312     NaN
313     NaN
314     NaN
315     NaN
316     3.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk16
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk16
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk16
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk16
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk16
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk16
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk16
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk16
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk16
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk16

     rating
0       NaN
1       NaN
2      28.0
3      76.0
4      85.0
..      ...
312     NaN
313     NaN
314     NaN
315     NaN
316     2.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk17
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk17
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk17
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk17
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk17
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk17
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk17
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk17
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk17
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk17

     rating
0       NaN
1       NaN
2      22.0
3      75.0
4      92.0
..      ...
312     NaN
313     NaN
314     NaN
315     NaN
316     2.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk18
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk18
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08  wk18
3    2000      3 Doors Down                    Loser  4:24   2000-10-21  wk18
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15  wk18
..    ...               ...                      ...   ...          ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  wk18
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  wk18
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  wk18
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  wk18
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  wk18

     rating
0       NaN
1       NaN
2      18.0
3      67.0
4      96.0
..      ...
312     NaN
313     NaN
314     NaN
315     NaN
316     3.0

[317 rows x 7 columns],      year            artist                    track  time date.entered  week  \

In [215]:
# 데이터 병합하기 : pd.merge()

In [216]:
person = pd.read_csv('../data/survey_person.csv')
site = pd.read_csv('../data/survey_site.csv')
survey = pd.read_csv('../data/survey_survey.csv')
visited = pd.read_csv('../data/survey_visited.csv')

print(person)

      ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth

In [217]:
print(site)

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [218]:
print(visited)

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [219]:
print(survey)

    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [220]:
# 일대일 병합하기

visited_subset = visited.loc[[0, 2, 6], :]
print(visited_subset)

   ident   site       dated
0    619   DR-1  1927-02-08
2    734   DR-3  1939-01-07
6    837  MSK-4  1932-01-14

In [221]:
print(visited_subset['site'].value_counts())

site
DR-1     1
DR-3     1
MSK-4    1
Name: count, dtype: int64

In [222]:
o2o_merge = site.merge(visited_subset, left_on='name', right_on='site')
print(o2o_merge)

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [223]:
# 다대일 병합하기

In [224]:
print(visited['site'].value_counts())

site
DR-3     4
DR-1     3
MSK-4    1
Name: count, dtype: int64

In [225]:
site

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [226]:
visited

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [227]:
m2o_merge = site.merge(visited, left_on='name', right_on='site')
print(m2o_merge)

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [228]:
# 다대다 병합

ps = person.merge(survey, left_on='ident', right_on='person')
vs = visited.merge(survey, left_on='ident', right_on='taken')
print(ps)

   ident   personal   family  taken person quant  reading
0   dyer    William     Dyer    619   dyer   rad     9.82
1   dyer    William     Dyer    619   dyer   sal     0.13
2   dyer    William     Dyer    622   dyer   rad     7.80
3   dyer    William     Dyer    622   dyer   sal     0.09
4     pb      Frank  Pabodie    734     pb   rad     8.41
5     pb      Frank  Pabodie    734     pb  temp   -21.50
6     pb      Frank  Pabodie    735     pb   rad     7.22
7     pb      Frank  Pabodie    751     pb   rad     4.35
8     pb      Frank  Pabodie    751     pb  temp   -18.50
9   lake   Anderson     Lake    734   lake   sal     0.05
10  lake   Anderson     Lake    751   lake   sal     0.10
11  lake   Anderson     Lake    752   lake   rad     2.19
12  lake   Anderson     Lake    752   lake   sal     0.09
13  lake   Anderson     Lake    752   lake  temp   -16.00
14  lake   Anderson     Lake    837   lake   rad     1.46
15  lake   Anderson     Lake    837   lake   sal     0.21
16   roe  Valentina  Roerich    752    roe   sal    41.60
17   roe  Valentina  Roerich    837    roe   sal    22.50
18   roe  Valentina  Roerich    844    roe   rad    11.25

In [229]:
print(vs)

    ident   site       dated  taken person quant  reading
0     619   DR-1  1927-02-08    619   dyer   rad     9.82
1     619   DR-1  1927-02-08    619   dyer   sal     0.13
2     622   DR-1  1927-02-10    622   dyer   rad     7.80
3     622   DR-1  1927-02-10    622   dyer   sal     0.09
4     734   DR-3  1939-01-07    734     pb   rad     8.41
5     734   DR-3  1939-01-07    734   lake   sal     0.05
6     734   DR-3  1939-01-07    734     pb  temp   -21.50
7     735   DR-3  1930-01-12    735     pb   rad     7.22
8     735   DR-3  1930-01-12    735    NaN   sal     0.06
9     735   DR-3  1930-01-12    735    NaN  temp   -26.00
10    751   DR-3  1930-02-26    751     pb   rad     4.35
11    751   DR-3  1930-02-26    751     pb  temp   -18.50
12    751   DR-3  1930-02-26    751   lake   sal     0.10
13    752   DR-3         NaN    752   lake   rad     2.19
14    752   DR-3         NaN    752   lake   sal     0.09
15    752   DR-3         NaN    752   lake  temp   -16.00
16    752   DR-3         NaN    752    roe   sal    41.60
17    837  MSK-4  1932-01-14    837   lake   rad     1.46
18    837  MSK-4  1932-01-14    837   lake   sal     0.21
19    837  MSK-4  1932-01-14    837    roe   sal    22.50
20    844   DR-1  1932-03-22    844    roe   rad    11.25

In [230]:
print(ps['quant'].value_counts())

quant
rad     8
sal     8
temp    3
Name: count, dtype: int64

In [231]:
ps_vs = ps.merge(
    vs, 
    left_on=['quant'],
    right_on=['quant']
)

ps_vs

,ident_x,personal,family,taken_x,person_x,quant,reading_x,ident_y,site,dated,taken_y,person_y,reading_y
0,dyer,William,Dyer,619,dyer,rad,9.82,619,DR-1,1927-02-08,619,dyer,9.82
1,dyer,William,Dyer,619,dyer,rad,9.82,622,DR-1,1927-02-10,622,dyer,7.80
2,dyer,William,Dyer,619,dyer,rad,9.82,734,DR-3,1939-01-07,734,pb,8.41
3,dyer,William,Dyer,619,dyer,rad,9.82,735,DR-3,1930-01-12,735,pb,7.22
4,dyer,William,Dyer,619,dyer,rad,9.82,751,DR-3,1930-02-26,751,pb,4.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,roe,Valentina,Roerich,844,roe,rad,11.25,735,DR-3,1930-01-12,735,pb,7.22
144,roe,Valentina,Roerich,844,roe,rad,11.25,751,DR-3,1930-02-26,751,pb,4.35
145,roe,Valentina,Roerich,844,roe,rad,11.25,752,DR-3,NaN,752,lake,2.19
146,roe,Valentina,Roerich,844,roe,rad,11.25,837,MSK-4,1932-01-14,837,lake,1.46
147,roe,Valentina,Roerich,844,roe,rad,11.25,844,DR-1,1932-03-22,844,roe,11.25

In [232]:
ps_vs['quant'].value_counts()

quant
sal     72
rad     64
temp    12
Name: count, dtype: int64

In [233]:
print(ps_vs.loc[0, :])

ident_x            dyer
personal        William
family             Dyer
taken_x             619
person_x           dyer
quant               rad
reading_x          9.82
ident_y             619
site               DR-1
dated        1927-02-08
taken_y             619
person_y           dyer
reading_y          9.82
Name: 0, dtype: object

In [234]:
print(ps.shape)

(19, 7)

In [235]:
print(vs.shape)

(21, 7)

In [236]:
print(ps_vs.shape)

(148, 13)

In [237]:
assert vs.shape[0] == 21

In [238]:
# assert ps_vs.shape[0] <= vs.shape[0] # 오류
assert ps_vs.shape[0] >= vs.shape[0]

In [239]:
# billboard 데이터에서 트랙의 주별 순위를 매기기 : 데이터 정규화

In [242]:
import pandas as pd

billboard = pd.read_csv('../data/billboard.csv')

billboard_long = billboard.melt(
    id_vars = ['year', 'artist', 'track', 'time', 'date.entered'],
    var_name = 'week', 
    value_name ='rating'
)

print(billboard_long)

       year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08
3      2000      3 Doors Down                    Loser  4:24   2000-10-21
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15
...     ...               ...                      ...   ...          ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29

       week  rating
0       wk1    87.0
1       wk1    91.0
2       wk1    81.0
3       wk1    76.0
4       wk1    57.0
...     ...     ...
24087  wk76     NaN
24088  wk76     NaN
24089  wk76     NaN
24090  wk76     NaN
24091  wk76     NaN

[24092 rows x 7 columns]

In [243]:
print(billboard_long.loc[billboard_long.track == 'Loser'])

       year        artist  track  time date.entered  week  rating
3      2000  3 Doors Down  Loser  4:24   2000-10-21   wk1    76.0
320    2000  3 Doors Down  Loser  4:24   2000-10-21   wk2    76.0
637    2000  3 Doors Down  Loser  4:24   2000-10-21   wk3    72.0
954    2000  3 Doors Down  Loser  4:24   2000-10-21   wk4    69.0
1271   2000  3 Doors Down  Loser  4:24   2000-10-21   wk5    67.0
...     ...           ...    ...   ...          ...   ...     ...
22510  2000  3 Doors Down  Loser  4:24   2000-10-21  wk72     NaN
22827  2000  3 Doors Down  Loser  4:24   2000-10-21  wk73     NaN
23144  2000  3 Doors Down  Loser  4:24   2000-10-21  wk74     NaN
23461  2000  3 Doors Down  Loser  4:24   2000-10-21  wk75     NaN
23778  2000  3 Doors Down  Loser  4:24   2000-10-21  wk76     NaN

[76 rows x 7 columns]

In [244]:
billboard_songs = billboard_long [
    ['year', 'artist', 'track', 'time', 'date.entered']
]

print(billboard_songs.shape)

(24092, 5)

In [245]:
billboard_songs

       year            artist                    track  time date.entered
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08
3      2000      3 Doors Down                    Loser  4:24   2000-10-21
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15
...     ...               ...                      ...   ...          ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29

[24092 rows x 5 columns]

In [ ]:
# 중복 제거 - 정규과 Normalization 과정
billboard_songs = billboard_songs.drop_duplicates()
print(billboard_songs.shape)

(317, 5)

In [ ]:
# column에 id를 추가한다, index에 + 1을 한다.

billboard_songs['id'] = billboard_songs.index + 1 
print(billboard_songs)

     year            artist                    track  time date.entered   id
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02    2
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08    3
3    2000      3 Doors Down                    Loser  4:24   2000-10-21    4
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15    5
..    ...               ...                      ...   ...          ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29  313
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01  314
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18  315
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02  316
316  2000   matchbox twenty                     Bent  4:12   2000-04-29  317

[317 rows x 6 columns]

In [248]:
billboard_ratings = billboard_songs.merge(
    billboard_long, on=['year', 'artist', 'track', 'time', 'date.entered']
)

print(billboard_ratings.shape)

(24092, 8)

In [249]:
print(billboard_ratings)

       year           artist                    track  time date.entered   id  \
0      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
1      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
2      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
3      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
4      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26    1
...     ...              ...                      ...   ...          ...  ...
24087  2000  matchbox twenty                     Bent  4:12   2000-04-29  317
24088  2000  matchbox twenty                     Bent  4:12   2000-04-29  317
24089  2000  matchbox twenty                     Bent  4:12   2000-04-29  317
24090  2000  matchbox twenty                     Bent  4:12   2000-04-29  317
24091  2000  matchbox twenty                     Bent  4:12   2000-04-29  317

       week  rating
0       wk1    87.0
1       wk2    82.0
2       wk3    72.0
3       wk4    77.0
4       wk5    87.0
...     ...     ...
24087  wk72     NaN
24088  wk73     NaN
24089  wk74     NaN
24090  wk75     NaN
24091  wk76     NaN

[24092 rows x 8 columns]

In [250]:
billboard_ratings = billboard_ratings[['id', 'week', 'rating']]

display(billboard_ratings)

        id  week  rating
0        1   wk1    87.0
1        1   wk2    82.0
2        1   wk3    72.0
3        1   wk4    77.0
4        1   wk5    87.0
...    ...   ...     ...
24087  317  wk72     NaN
24088  317  wk73     NaN
24089  317  wk74     NaN
24090  317  wk75     NaN
24091  317  wk76     NaN

[24092 rows x 3 columns]